apiVersion: v1
kind: Service
metadata:
  labels:
    app: cvapp
  name: cvapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30000
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: rv0lt/mycv
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "200m"